# cmake/NvrDefs.cmake
# SIMPLE, BUCKET-BY-NAME DEFS COLLECTOR (no scopes, no begin/end, no magic)
#
# You can do exactly:
#   nvr_defs_init(core)
#   nvr_defs_init(lib1)
#   nvr_defs_init(lib2)
#   nvr_defs_init(binary)
#   nvr_defs_add(lib2 NVR_LIB2=1)
#   nvr_defs_add(core NVR_CORE=1 NVR_USE_FAST_MATH=1)
#   add_library(navary_lib2 src/lib2.cc)
#   nvr_defs_apply(lib2 navary_lib2 PUBLIC)
#
# Buckets are independent. You can call nvr_defs_add(...) repeatedly anywhere.
# Items are deduplicated. ON/OFF/TRUE/FALSE/YES/NO normalize to 1/0.

# ---- internals: store each bucket in a global property by its name ----
function(_nvr_defs_key NAME OUT)
  if(NOT NAME)
    message(FATAL_ERROR "nvr_defs: empty bucket name")
  endif()
  set(${OUT} "NVR_DEFS_BUCKET/${NAME}" PARENT_SCOPE)
endfunction()

function(_nvr_defs_ensure NAME)
  _nvr_defs_key("${NAME}" _KEY)
  get_property(_have GLOBAL PROPERTY "${_KEY}/INIT" SET)
  if(NOT _have)
    set_property(GLOBAL PROPERTY "${_KEY}" "")
    set_property(GLOBAL PROPERTY "${_KEY}/INIT" TRUE)
  endif()
endfunction()

function(_nvr_defs_get NAME OUT_VAR)
  _nvr_defs_ensure("${NAME}")
  _nvr_defs_key("${NAME}" _KEY)
  get_property(_lst GLOBAL PROPERTY "${_KEY}")
  if(NOT _lst)
    set(_lst "")
  endif()
  set(${OUT_VAR} "${_lst}" PARENT_SCOPE)
endfunction()

function(_nvr_defs_set NAME LIST_IN)
  _nvr_defs_key("${NAME}" _KEY)
  set_property(GLOBAL PROPERTY "${_KEY}" "${LIST_IN}")
endfunction()

function(_nvr_defs_norm_bool IN OUT_VAR)
  string(TOUPPER "${IN}" _UP)
  if(_UP STREQUAL "ON" OR _UP STREQUAL "TRUE" OR _UP STREQUAL "YES")
    set(${OUT_VAR} "1" PARENT_SCOPE)
  elseif(_UP STREQUAL "OFF" OR _UP STREQUAL "FALSE" OR _UP STREQUAL "NO")
    set(${OUT_VAR} "0" PARENT_SCOPE)
  else()
    set(${OUT_VAR} "${IN}" PARENT_SCOPE)
  endif()
endfunction()

# ---- public API ----

function(nvr_defs_init NAME)
  _nvr_defs_ensure("${NAME}")
endfunction()

function(nvr_defs_clear NAME)
  _nvr_defs_set("${NAME}" "")
endfunction()

function(nvr_defs_add NAME)
  if(NOT ARGN)
    return()
  endif()
  _nvr_defs_get("${NAME}" _cur)
  set(_set "${_cur}")
  foreach(_def IN LISTS ARGN)
    if(_def MATCHES "^[^=]+=")
      string(REPLACE "=" ";" _pair "${_def}")
      list(GET _pair 0 _k)
      list(GET _pair 1 _v)
      _nvr_defs_norm_bool("${_v}" _vnorm)
      set(_norm "${_k}=${_vnorm}")
    else()
      # bare symbol (kept as-is); do not normalize
      set(_norm "${_def}")
    endif()
    list(FIND _set "${_norm}" _idx)
    if(_idx EQUAL -1)
      list(APPEND _set "${_norm}")
    endif()
  endforeach()
  _nvr_defs_set("${NAME}" "${_set}")
endfunction()

function(nvr_defs_add_if NAME CONDITION DEF)
  if(${CONDITION})
    if(ARGC GREATER 3)
      set(_val "${ARGV3}")
      _nvr_defs_norm_bool("${_val}" _valnorm)
      nvr_defs_add("${NAME}" "${DEF}=${_valnorm}")
    else()
      nvr_defs_add("${NAME}" "${DEF}")
    endif()
  endif()
endfunction()

function(nvr_defs_merge DST SRC)
  _nvr_defs_get("${DST}" _dst)
  _nvr_defs_get("${SRC}" _src)
  foreach(_d IN LISTS _src)
    list(FIND _dst "${_d}" _idx)
    if(_idx EQUAL -1)
      list(APPEND _dst "${_d}")
    endif()
  endforeach()
  _nvr_defs_set("${DST}" "${_dst}")
endfunction()

function(nvr_defs_get NAME OUT_VAR)
  _nvr_defs_get("${NAME}" _lst)
  set(${OUT_VAR} "${_lst}" PARENT_SCOPE)
endfunction()

function(nvr_defs_apply NAME TARGET)
  if(NOT TARGET ${TARGET})
    message(FATAL_ERROR "nvr_defs_apply: target '${TARGET}' does not exist")
  endif()
  set(_scope "PRIVATE")
  if(ARGC GREATER 2)
    set(_scope "${ARGV2}")
  endif()
  _nvr_defs_get("${NAME}" _lst)
  if(_lst)
    target_compile_definitions(${TARGET} ${_scope} ${_lst})
  endif()
endfunction()

function(nvr_defs_dump NAME)
  _nvr_defs_get("${NAME}" _lst)
  if(_lst)
    string(JOIN " " _flat ${_lst})
    message(STATUS "[nvr_defs '${NAME}'] ${_flat}")
  else()
    message(STATUS "[nvr_defs '${NAME}'] (empty)")
  endif()
endfunction()
